name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - lang-pt  # Or your default branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r workshop/content/requirements.txt

      - name: Build MkDocs site
        run: mkdocs gh-deploy --config-file workshop/content/mkdocs.yml --force --clean